### PR TITLE
Doc fix

### PR DESCRIPTION
**Pull request by pelger**

### CODE REVIEW

**Comment by mcollina** [comment]
Can you submit this PR against https://github.com/nearform/nscale/pull/60? It also has the CHANGELOG update and some more README fixes.

**Comment by darragh-hayes** [comment]
I've gone over it and just made some very small changes. I was thinking that maybe we could mention installing node using nvm? I remember this was the case with one of our other docs.

**Comment by mcollina** [comment]
@darragh-hayes I would leave this as a it is, and fix sudc-system as explained in https://github.com/nearform/sudc-system/issues/10#issuecomment-76526218.

**Comment by darragh-hayes** [comment]
Sure thing. I'll send a PR for it soon.

**Comment by mcollina** [comment]
I also added my fixes :).

**Pull request merged**
